### ISSUE TITLE
Does its support make it clickable to open another note?

### ISSUE THREAD

**Issue by loctv** [inkdropapp/inkdrop-mermaid#11]
I am interest of write a C4 model docs. It does need to many diagrams that can be jump between of them. Is there any way to click on a graph to open another graph or a different note?

**Comment by craftzdog** [comment]
I guess Mermaid doesn't support using `a` tags in C4 diagrams, perhaps.

**Comment by loctv** [comment]
> I guess Mermaid doesn't support using `a` tags in C4 diagrams, perhaps.

Yes I understood. I will use an anchor link in the description. I like the simplicity of the Mermaid syntax in markdown instead of use a full-featured DSL
