### ISSUE TITLE
Specifying `tickInterval` causing Parse Error; upgrade mermaid to >=9.3?

### ISSUE THREAD

**Issue by m-e-shum** [inkdropapp/inkdrop-mermaid#14]
Hi, 

I was wondering if you can upgrade the plugin to use mermaid >= v9.3.0. In v9.3.0, mermaid adds a `tickInterval` option to gantt charts (https://github.com/mermaid-js/mermaid/pull/3729).

Example code to reproduce error in inkdrop-mermaid v.2.5.2.
```
gantt
    title Roadmap
    dateFormat MM-YYYY
    axisFormat %b %Y
    tickInterval 1month
    excludes 07-2023
    
    section Section
    Task :crit, done, a1, 05-2023, 1M
```

Inkdrop render message
![inkdrop_mermaid_error](https://github.com/inkdropapp/inkdrop-mermaid/assets/10886807/8affd6a2-ccbd-41b1-ad05-9a78388c9ef5)

**Comment by craftzdog** [comment]
Okay,
Just bumped up Mermaid to v9.4.3 now!
