### ISSUE TITLE
Sequence Diagram: Actor Creation and Destruction not available

### ISSUE THREAD

**Issue by jmauriciosalasmoreno** [inkdropapp/inkdrop-mermaid#17]
Sequence Diagram Actor Creation and Destruction [is added](https://mermaid.js.org/syntax/sequenceDiagram.html#actor-creation-and-destruction-v10-3-0) on mermaid  v10.3.0

inkdrop-mermaid [current version is 9.4.3](https://github.com/inkdropapp/inkdrop-mermaid/blob/02c67629cd4d44ca92d5bfd8b81a710b53cdaf21/package.json#L13)

![image](https://github.com/inkdropapp/inkdrop-mermaid/assets/85201361/3bf08c50-6752-4ce7-acdf-d822ceef9892)

**Comment by johmsalas** [comment]
I tried upgrading in the package.json but got this error in InkDrop:

<img width="585" alt="image" src="https://github.com/inkdropapp/inkdrop-mermaid/assets/6575405/046d8e0e-1fec-465d-89b8-6bf53f19568a">

**Comment by johmsalas** [comment]
Tried this approach https://github.com/0x6b/mermaid-cli-rs/blob/db7ed83df4d68604e5511549616a9a615086f39c/assets/index.html#L16C33-L16C33. Now I'm getting 
<img width="548" alt="image" src="https://github.com/inkdropapp/inkdrop-mermaid/assets/6575405/a1372170-e10d-4570-9824-deacf86f4400">

**Comment by johmsalas** [comment]
Made it work. I should be able to post a PR later today.
@craftzdog some guidelines I should take into account?

<img width="1090" alt="image" src="https://github.com/inkdropapp/inkdrop-mermaid/assets/6575405/0f60ad58-ef49-4cb5-84d3-60258c6cf2de">

**Comment by jmauriciosalasmoreno** [comment]
@craftzdog  Shall this issue be open until there is a release?

**Comment by craftzdog** [comment]
It can be closed. I'll release it when v5.6.3 is out
