### ISSUE TITLE
Theming support doesn't take export into account

### ISSUE THREAD

**Issue by malachid** [inkdropapp/inkdrop-mermaid#6]
1. Set Inkdrop to Dark mode w/ Dark content
2. When you use Mermaid, you'll end up wanting to use the Dark mode in it to match
3. If you export as PDF, the page is not in dark mode so the mermaid diagram doesn't match the output

Recommendation would be to have a separate in-app theme setting vs print theme setting.

**Comment by craftzdog** [comment]
Thanks for the report.
Yeah agree but it's not possible to determine if it's print or not at the moment.
I'll consider adding React Context or something to make it possible in the future.
